esphome:
  name: esp32_dwell_test
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 2min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Dwell Fallback Hotspot"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd

ota:
  password: !secret ota_passwd

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    name: "water_flow"
    pin:
      number: 13
      mode: INPUT_PULLUP

sensor:
  - platform: uptime
    name: Dwell uptime
    id: dwell_uptime
    update_interval: 60s

  - platform: bmp085
    temperature:
      name: "Dwell box temperature"
      id: dwell_box_temp
    pressure:
      name: "Air Pressure"
      id: "p_atm"
    update_interval: 60s


  - platform: adc
    pin: A0
    name: "Water pressure sensor"
    update_interval: 60s
    attenuation: 6db
    id: "v_adc"

switch:
  - platform: gpio
    pin: 33
    name: pump_relay_out_33
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 32
    name: d32
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 27
    name: d27
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 23
    name: d23
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 19
    name: d19
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 18
    name: d18
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 17
    name: d17
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 16
    name: d16
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 04
    name: d04
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 02
    name: wdt_out_02
    id: wdt_out_02
    restore_mode: ALWAYS_OFF

interval:
  - interval: 1sec
    then:
      - switch.toggle: wdt_out_02

