esphome:
  name: gates_8266
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 2min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gates Fallback Hotspot"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd

ota:
  password: !secret ota_passwd

globals:
  - id: time_opening
    type: int
    initial_value: '0'

switch:
  - platform: gpio
    pin: GPIO12
    id: "led"
    inverted: yes
    internal: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO5
    id: "rel"
    internal: true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "Gate button"
    icon: "mdi:gate"
    id: "gate_button"
    turn_on_action:
    - if:
        condition:
          lambda: 'return (id(gates_uptime).state - id(time_opening)) < 40;'
        then:
          - logger.log: 'Not toggling, protection interval not passed'
        else:
          - switch.turn_on: rel
          - switch.turn_on: led
          - delay: 500ms
          - switch.turn_off: rel
          - switch.turn_off: led
          - lambda: id(time_opening) = id(gates_uptime).state;

sensor:
  - platform: uptime
    name: Gates uptime
    id: gates_uptime
    update_interval: 10s
  - platform: wifi_signal
    name: "Gates RSSI"
    update_interval: 60s
  - platform: adc
    pin: A0
    name: "Gates ADC"
    update_interval: 10s
  - platform: dallas
    address: 0xB0000003D5E18128
    name: "Gates control temperature"

web_server:
  port: 80

dallas:
  pin: GPIO13

