esphome:
  name: hall_window_switch
  platform: ESP8266
  board: esp_wroom_02

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 2min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
   ssid: "hall window Hotspot"
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd

ota:
  password: !secret ota_passwd

web_server:
  port: 80

status_led:
  pin: GPIO16
  
output:
  - platform: gpio
    pin: 15
    id: relay1

light:
  - platform: binary
    name: 'light_switch_relay1'
    id: light_switch_relay1
    output: relay1
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    pin: 5
    filters:
      - invert:
      - delayed_on: 20ms
    name: switch_button1
    id: switch_button1
    on_release:
      then:
        - light.toggle: light_switch_relay1
