esphome:
  name: otgw
  platform: ESP32
  board: esp32doit-devkit-v1
  libraries:
    - OpenTherm Library
  includes:
    - my.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 2min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 otgw Fallback Hotspot"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:

switch:
    - platform: gpio
      name: "LED 1"
      id: "led_1"
      pin: 2

binary_sensor:
    - platform: gpio
      name: "Button 1"
      pin:
          number: 0
          inverted: True

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyCustomSensor();
    App.register_component(my_sensor);
    return {my_sensor->heatant_temp, my_sensor->burner_modulation};

  sensors:
    name: "My Custom Sensor"
