esphome:
  name: test_esp32
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 2min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Esp32 Fallback Hotspot"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd

ota:
  password: !secret ota_passwd

esp32_ble_tracker:
  scan_parameters:
    window: 100ms

switch:
  - platform: gpio
    name: "LED"
    pin: 2
    id: "LED_1"
  - platform: gpio
    name: "Relay"
    pin: 33
    id: "relay_1"

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "BUTTON"
    filters:
      - invert:
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: LED_1
        - delay: 2s
        - switch.turn_off: LED_1
  - platform: ble_presence
    mac_address: 7C:2F:80:EA:FA:10
    name: "Gigaset G-tag orange"

web_server:
  port: 80

# Example configuration entry
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

# Example configuration entry
sensor:
  - platform: bmp085
    temperature:
      name: "Outside Temperature"
    pressure:
      name: "Outside Pressure"
    update_interval: 60s
